   version: '3'
   services:
     postgres:
       container_name: postgres
       image: postgres:15
       volumes:
         - ./postgres-data:/var/lib/postgresql/data
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: main
       ports:
         - "127.0.0.1:25432:5432"
       networks:
         - main_network
       restart: always
       init: true

   volumes:
     postgres-data:

   networks:
     main_network:
       driver: bridge
   
