version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - "127.0.0.1:25432:5432"
    networks:
      - main_network
    restart: always

volumes:
  postgres-data:

networks:
  main_network:
    driver: bridge
